### ISSUE TITLE
Front page example should have detection_type value enclosed with quotes

### ISSUE THREAD

**Issue by OzWookiee** [HandsetDetection/logstash-filter-handsetdetection#14]
The front page configuration example shows

> filter { 
>         grok { 
>             match => {  
>                 "message" => "%{COMBINEDAPACHELOG}" 
>             } 
>         } 
>         handsetdetection {
>             username   => "xxxxxxxxxx" 
>             password   => "xxxxxxxxxxxxxxxx"
>             site_id    => 000000
>             **detection_type   => ultimate**
>             match      => { 
>                 "agent" => "user-agent" 
>             }
>             filter     => [
>                 "general_vendor", "general_model", "general_type"
>             ]
>         } 
>     }
> 

Following this will throw an error concerning detection_type unknown. This is because the value, ultimate, should be enclosed in quotes:
`            detection_type   => "ultimate"`

**Comment by OzWookiee** [comment]
P.S. The installation can drop the versioning and just be:
`bin/logstash-plugin install logstash-filter-handsetdetection`

**Comment by OzWookiee** [comment]
Submitted pull: https://github.com/HandsetDetection/logstash-filter-handsetdetection/pull/15

**Comment by elricho** [comment]
Merged

**Comment by elricho** [comment]
👍
